### PR TITLE
Update Dependency

### LINKED ISSUE #4: Dependency Update: use Minmatch 3.0.2 or higher to avoid a RegExp DoS issue
When installing a module that uses this module as a dependency, I am getting warnings about `minmatch`: 

> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

I believe the problem lies in the dependenies of `node-findup-sync`, which is currently on [`v0.4.x`](https://github.com/js-cli/node-findup-sync/blob/master/package.json#L4) where this module currently uses [^v0.2.1](https://github.com/callumacrae/find-node-modules/blob/659662ad612f1c3aeeb95a63ba30ed0910552d47/package.json#L20)

### PR DESCRIPTION
**Pull request by zedd45**
- update `findup-sync` dependency to `^v0.4.1`

Tests appear to hang, locally.  Hopefully this is just a local issue...?

Fixes #4

### CODE REVIEW

**Comment by kentcdodds** [comment]
ping. This outdated module is responsible for this error pretty much every time I run npm install:

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

**Comment by callumacrae** [comment]
Does this actually work, though? Last time we did this, everything broke: https://github.com/callumacrae/find-node-modules/pull/2

Here's the issue from last time: https://github.com/callumacrae/find-node-modules/issues/3

Sorry for the huge delay on this, I don't actually use this project any more and have been away. Back at work now so will respond quicker :)

**Comment by zedd45** [comment]
I was worried about the fact that the tests hung, but I was hoping a local run by the maintainer might spot something I missed.  That's worrisome that it broke before, and that it hangs locally for me.

**Comment by callumacrae** [comment]
Nothing in the findup-sync changelog suggests this should be happening. Bit confused.

**Comment by callumacrae** [comment]
Fixed in https://github.com/callumacrae/find-node-modules/pull/7 as find-node-modules@1.0.4

**Pull request closed without merging**
